### ISSUE TITLE
'Stop' on jupyter notebook does not stop running solver

### ISSUE THREAD

**Issue by briandrawert** [StochSS/GillesPy2#327] opened 2020-04-16 12:02 UTC
This seems to be new in 1.3.* possibly just with BasicTauHybridSolver.  I suspect that our use of threads is preventing the stop from working.

**Comment by seanebum** [comment] 2020-06-11 19:36
This issue exists only with the BasicTauHybridSolver.   It seems to be caused by the way we are using solve_ivp.  I think the best fix for this is going to be a bit of a refactor, and may be good incentive to produce a C++ powered version.

**Comment by ethangreen-dev** [comment] 2022-05-16 18:51
Closing in favor of #662.

**Closed by ethangreen-dev** 2022-05-16 18:51 UTC
